CREATE DATABASE WESPLITAPP
GO

USE WESPLITAPP
GO

CREATE TABLE [TRIP] (
  [TRIP_ID] int PRIMARY KEY IDENTITY(1, 1),
  [TITTLE] nvarchar(255) UNIQUE NOT NULL,
  [DESCRIPTION] nvarchar(255),
  [THUMNAILIMAGE] nvarchar(255) NOT NULL,
  [CURRENTPROCEEDS] float NOT NULL DEFAULT 0,
  [TOTALCOSTS] float NOT NULL DEFAULT 0,
  [TOGODATE] datetime,
  [RETURNDATE] datetime,
  [ISDONE] bit
)
GO

CREATE TABLE [MEMBER] (
  [MEMBER_ID] int PRIMARY KEY IDENTITY(1, 1),
  [NAME] nvarchar(255) UNIQUE NOT NULL,
  [PHONENUMBER] numeric NOT NULL,
  [GENDER] bit,
  [AVATAR] nvarchar(255) UNIQUE NOT NULL
)
GO

CREATE TABLE [LOCATION] (
  [LOCATION_ID] int PRIMARY KEY IDENTITY(1, 1),
  [NAME] nvarchar(255) UNIQUE NOT NULL,
  [ADDRESS] nvarchar(255) UNIQUE NOT NULL,
  [DESCRIPTION] nvarchar(255),
  [TYPE] bit
)
GO

CREATE TABLE [TRIP_MEMBER] (
  [TRIP_ID] int,
  [MEMBER_ID] int,
  [AMOUNTPAID] float NOT NULL DEFAULT 0,
  PRIMARY KEY ([TRIP_ID], [MEMBER_ID])
)
GO

CREATE TABLE [TRIP_LOCATION] (
  [TRIP_ID] int,
  [LOCATION_ID] int,
  [COSTS] float NOT NULL DEFAULT 0,
  PRIMARY KEY ([TRIP_ID], [LOCATION_ID])
)
GO

ALTER TABLE [TRIP_MEMBER] ADD FOREIGN KEY ([TRIP_ID]) REFERENCES [TRIP] ([TRIP_ID])
GO

ALTER TABLE [TRIP_MEMBER] ADD FOREIGN KEY ([MEMBER_ID]) REFERENCES [MEMBER] ([MEMBER_ID])
GO

ALTER TABLE [TRIP_LOCATION] ADD FOREIGN KEY ([TRIP_ID]) REFERENCES [TRIP] ([TRIP_ID])
GO

ALTER TABLE [TRIP_LOCATION] ADD FOREIGN KEY ([LOCATION_ID]) REFERENCES [LOCATION] ([LOCATION_ID])
GO