<?xml version="1.0" encoding="utf-8"?><Database Name="WESPLITAPP" Class="DataLocationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-049JUV9\SQLEXPRESS;Initial Catalog=WESPLITAPP;Integrated Security=True" SettingsObjectName="WeSplitApp.Properties.Settings" SettingsPropertyName="WESPLITAPPConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LOCATION" Member="LOCATIONs">
    <Type Name="LOCATION">
      <Column Name="LOCATION_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOCATION_TRIP_LOCATION" Member="TRIP_LOCATIONs" ThisKey="LOCATION_ID" OtherKey="LOCATION_ID" Type="TRIP_LOCATION" />
    </Type>
  </Table>
  <Table Name="dbo.MEMBER" Member="MEMBERs">
    <Type Name="MEMBER">
      <Column Name="MEMBER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PHONENUMBER" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AVATAR" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="MEMBER_TRIP_MEMBER" Member="TRIP_MEMBERs" ThisKey="MEMBER_ID" OtherKey="MEMBER_ID" Type="TRIP_MEMBER" />
    </Type>
  </Table>
  <Table Name="dbo.TRIP" Member="TRIPs">
    <Type Name="TRIP">
      <Column Name="TRIP_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TITTLE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="THUMNAILIMAGE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CURRENTPROCEEDS" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TOTALCOSTS" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TOGODATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RETURNDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISDONE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TRIP_TRIP_COSTINCURRED" Member="TRIP_COSTINCURREDs" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP_COSTINCURRED" />
      <Association Name="TRIP_TRIP_IMAGE" Member="TRIP_IMAGEs" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP_IMAGE" />
      <Association Name="TRIP_TRIP_LOCATION" Member="TRIP_LOCATIONs" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP_LOCATION" />
      <Association Name="TRIP_TRIP_MEMBER" Member="TRIP_MEMBERs" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP_MEMBER" />
    </Type>
  </Table>
  <Table Name="dbo.TRIP_COSTINCURRED" Member="TRIP_COSTINCURREDs">
    <Type Name="TRIP_COSTINCURRED">
      <Column Name="COST_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TRIP_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COST" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TRIP_TRIP_COSTINCURRED" Member="TRIP" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP" IsForeignKey="true" />
      <Association Name="COSTINCURRED_TRIP_COSTINCURRED" Member="COSTINCURRED" ThisKey="COST_ID" OtherKey="COST_ID" Type="COSTINCURRED" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRIP_IMAGES" Member="TRIP_IMAGEs">
    <Type Name="TRIP_IMAGE">
      <Column Name="TRIP_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IMAGE" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TRIP_TRIP_IMAGE" Member="TRIP" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRIP_LOCATION" Member="TRIP_LOCATIONs">
    <Type Name="TRIP_LOCATION">
      <Column Name="TRIP_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LOCATION_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COSTS" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="LOCATION_TRIP_LOCATION" Member="LOCATION" ThisKey="LOCATION_ID" OtherKey="LOCATION_ID" Type="LOCATION" IsForeignKey="true" />
      <Association Name="TRIP_TRIP_LOCATION" Member="TRIP" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRIP_MEMBER" Member="TRIP_MEMBERs">
    <Type Name="TRIP_MEMBER">
      <Column Name="TRIP_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MEMBER_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AMOUNTPAID" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="MEMBER_TRIP_MEMBER" Member="MEMBER" ThisKey="MEMBER_ID" OtherKey="MEMBER_ID" Type="MEMBER" IsForeignKey="true" />
      <Association Name="TRIP_TRIP_MEMBER" Member="TRIP" ThisKey="TRIP_ID" OtherKey="TRIP_ID" Type="TRIP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.COSTINCURRED" Member="COSTINCURREDs">
    <Type Name="COSTINCURRED">
      <Column Name="COST_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="COSTINCURRED_TRIP_COSTINCURRED" Member="TRIP_COSTINCURREDs" ThisKey="COST_ID" OtherKey="COST_ID" Type="TRIP_COSTINCURRED" />
    </Type>
  </Table>
</Database>