#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Resources
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WESPLITAPP")]
	public partial class DataLocationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLOCATION(LOCATION instance);
    partial void UpdateLOCATION(LOCATION instance);
    partial void DeleteLOCATION(LOCATION instance);
    partial void InsertMEMBER(MEMBER instance);
    partial void UpdateMEMBER(MEMBER instance);
    partial void DeleteMEMBER(MEMBER instance);
    partial void InsertTRIP(TRIP instance);
    partial void UpdateTRIP(TRIP instance);
    partial void DeleteTRIP(TRIP instance);
    partial void InsertTRIP_COSTINCURRED(TRIP_COSTINCURRED instance);
    partial void UpdateTRIP_COSTINCURRED(TRIP_COSTINCURRED instance);
    partial void DeleteTRIP_COSTINCURRED(TRIP_COSTINCURRED instance);
    partial void InsertTRIP_IMAGE(TRIP_IMAGE instance);
    partial void UpdateTRIP_IMAGE(TRIP_IMAGE instance);
    partial void DeleteTRIP_IMAGE(TRIP_IMAGE instance);
    partial void InsertTRIP_LOCATION(TRIP_LOCATION instance);
    partial void UpdateTRIP_LOCATION(TRIP_LOCATION instance);
    partial void DeleteTRIP_LOCATION(TRIP_LOCATION instance);
    partial void InsertTRIP_MEMBER(TRIP_MEMBER instance);
    partial void UpdateTRIP_MEMBER(TRIP_MEMBER instance);
    partial void DeleteTRIP_MEMBER(TRIP_MEMBER instance);
    partial void InsertCOSTINCURRED(COSTINCURRED instance);
    partial void UpdateCOSTINCURRED(COSTINCURRED instance);
    partial void DeleteCOSTINCURRED(COSTINCURRED instance);
    #endregion
		
		public DataLocationDataContext() : 
				base(global::WeSplitApp.Properties.Settings.Default.WESPLITAPPConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataLocationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLocationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLocationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLocationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOCATION> LOCATIONs
		{
			get
			{
				return this.GetTable<LOCATION>();
			}
		}
		
		public System.Data.Linq.Table<MEMBER> MEMBERs
		{
			get
			{
				return this.GetTable<MEMBER>();
			}
		}
		
		public System.Data.Linq.Table<TRIP> TRIPs
		{
			get
			{
				return this.GetTable<TRIP>();
			}
		}
		
		public System.Data.Linq.Table<TRIP_COSTINCURRED> TRIP_COSTINCURREDs
		{
			get
			{
				return this.GetTable<TRIP_COSTINCURRED>();
			}
		}
		
		public System.Data.Linq.Table<TRIP_IMAGE> TRIP_IMAGEs
		{
			get
			{
				return this.GetTable<TRIP_IMAGE>();
			}
		}
		
		public System.Data.Linq.Table<TRIP_LOCATION> TRIP_LOCATIONs
		{
			get
			{
				return this.GetTable<TRIP_LOCATION>();
			}
		}
		
		public System.Data.Linq.Table<TRIP_MEMBER> TRIP_MEMBERs
		{
			get
			{
				return this.GetTable<TRIP_MEMBER>();
			}
		}
		
		public System.Data.Linq.Table<COSTINCURRED> COSTINCURREDs
		{
			get
			{
				return this.GetTable<COSTINCURRED>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOCATION")]
	public partial class LOCATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LOCATION_ID;
		
		private string _NAME;
		
		private string _ADDRESS;
		
		private string _DESCRIPTION;
		
		private System.Nullable<bool> _TYPE;
		
		private EntitySet<TRIP_LOCATION> _TRIP_LOCATIONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOCATION_IDChanging(int value);
    partial void OnLOCATION_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnTYPEChanging(System.Nullable<bool> value);
    partial void OnTYPEChanged();
    #endregion
		
		public LOCATION()
		{
			this._TRIP_LOCATIONs = new EntitySet<TRIP_LOCATION>(new Action<TRIP_LOCATION>(this.attach_TRIP_LOCATIONs), new Action<TRIP_LOCATION>(this.detach_TRIP_LOCATIONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LOCATION_ID
		{
			get
			{
				return this._LOCATION_ID;
			}
			set
			{
				if ((this._LOCATION_ID != value))
				{
					this.OnLOCATION_IDChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_ID = value;
					this.SendPropertyChanged("LOCATION_ID");
					this.OnLOCATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(255)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Bit")]
		public System.Nullable<bool> TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOCATION_TRIP_LOCATION", Storage="_TRIP_LOCATIONs", ThisKey="LOCATION_ID", OtherKey="LOCATION_ID")]
		public EntitySet<TRIP_LOCATION> TRIP_LOCATIONs
		{
			get
			{
				return this._TRIP_LOCATIONs;
			}
			set
			{
				this._TRIP_LOCATIONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRIP_LOCATIONs(TRIP_LOCATION entity)
		{
			this.SendPropertyChanging();
			entity.LOCATION = this;
		}
		
		private void detach_TRIP_LOCATIONs(TRIP_LOCATION entity)
		{
			this.SendPropertyChanging();
			entity.LOCATION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MEMBER")]
	public partial class MEMBER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MEMBER_ID;
		
		private string _NAME;
		
		private decimal _PHONENUMBER;
		
		private System.Nullable<bool> _GENDER;
		
		private string _AVATAR;
		
		private EntitySet<TRIP_MEMBER> _TRIP_MEMBERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMEMBER_IDChanging(int value);
    partial void OnMEMBER_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPHONENUMBERChanging(decimal value);
    partial void OnPHONENUMBERChanged();
    partial void OnGENDERChanging(System.Nullable<bool> value);
    partial void OnGENDERChanged();
    partial void OnAVATARChanging(string value);
    partial void OnAVATARChanged();
    #endregion
		
		public MEMBER()
		{
			this._TRIP_MEMBERs = new EntitySet<TRIP_MEMBER>(new Action<TRIP_MEMBER>(this.attach_TRIP_MEMBERs), new Action<TRIP_MEMBER>(this.detach_TRIP_MEMBERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MEMBER_ID
		{
			get
			{
				return this._MEMBER_ID;
			}
			set
			{
				if ((this._MEMBER_ID != value))
				{
					this.OnMEMBER_IDChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_ID = value;
					this.SendPropertyChanged("MEMBER_ID");
					this.OnMEMBER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONENUMBER", DbType="Decimal(18,0) NOT NULL")]
		public decimal PHONENUMBER
		{
			get
			{
				return this._PHONENUMBER;
			}
			set
			{
				if ((this._PHONENUMBER != value))
				{
					this.OnPHONENUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONENUMBER = value;
					this.SendPropertyChanged("PHONENUMBER");
					this.OnPHONENUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="Bit")]
		public System.Nullable<bool> GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this.OnGENDERChanging(value);
					this.SendPropertyChanging();
					this._GENDER = value;
					this.SendPropertyChanged("GENDER");
					this.OnGENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this.OnAVATARChanging(value);
					this.SendPropertyChanging();
					this._AVATAR = value;
					this.SendPropertyChanged("AVATAR");
					this.OnAVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MEMBER_TRIP_MEMBER", Storage="_TRIP_MEMBERs", ThisKey="MEMBER_ID", OtherKey="MEMBER_ID")]
		public EntitySet<TRIP_MEMBER> TRIP_MEMBERs
		{
			get
			{
				return this._TRIP_MEMBERs;
			}
			set
			{
				this._TRIP_MEMBERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRIP_MEMBERs(TRIP_MEMBER entity)
		{
			this.SendPropertyChanging();
			entity.MEMBER = this;
		}
		
		private void detach_TRIP_MEMBERs(TRIP_MEMBER entity)
		{
			this.SendPropertyChanging();
			entity.MEMBER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRIP")]
	public partial class TRIP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TRIP_ID;
		
		private string _TITTLE;
		
		private string _DESCRIPTION;
		
		private string _THUMNAILIMAGE;
		
		private double _CURRENTPROCEEDS;
		
		private double _TOTALCOSTS;
		
		private System.Nullable<System.DateTime> _TOGODATE;
		
		private System.Nullable<System.DateTime> _RETURNDATE;
		
		private System.Nullable<bool> _ISDONE;
		
		private EntitySet<TRIP_COSTINCURRED> _TRIP_COSTINCURREDs;
		
		private EntitySet<TRIP_IMAGE> _TRIP_IMAGEs;
		
		private EntitySet<TRIP_LOCATION> _TRIP_LOCATIONs;
		
		private EntitySet<TRIP_MEMBER> _TRIP_MEMBERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRIP_IDChanging(int value);
    partial void OnTRIP_IDChanged();
    partial void OnTITTLEChanging(string value);
    partial void OnTITTLEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnTHUMNAILIMAGEChanging(string value);
    partial void OnTHUMNAILIMAGEChanged();
    partial void OnCURRENTPROCEEDSChanging(double value);
    partial void OnCURRENTPROCEEDSChanged();
    partial void OnTOTALCOSTSChanging(double value);
    partial void OnTOTALCOSTSChanged();
    partial void OnTOGODATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTOGODATEChanged();
    partial void OnRETURNDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnRETURNDATEChanged();
    partial void OnISDONEChanging(System.Nullable<bool> value);
    partial void OnISDONEChanged();
    #endregion
		
		public TRIP()
		{
			this._TRIP_COSTINCURREDs = new EntitySet<TRIP_COSTINCURRED>(new Action<TRIP_COSTINCURRED>(this.attach_TRIP_COSTINCURREDs), new Action<TRIP_COSTINCURRED>(this.detach_TRIP_COSTINCURREDs));
			this._TRIP_IMAGEs = new EntitySet<TRIP_IMAGE>(new Action<TRIP_IMAGE>(this.attach_TRIP_IMAGEs), new Action<TRIP_IMAGE>(this.detach_TRIP_IMAGEs));
			this._TRIP_LOCATIONs = new EntitySet<TRIP_LOCATION>(new Action<TRIP_LOCATION>(this.attach_TRIP_LOCATIONs), new Action<TRIP_LOCATION>(this.detach_TRIP_LOCATIONs));
			this._TRIP_MEMBERs = new EntitySet<TRIP_MEMBER>(new Action<TRIP_MEMBER>(this.attach_TRIP_MEMBERs), new Action<TRIP_MEMBER>(this.detach_TRIP_MEMBERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TRIP_ID
		{
			get
			{
				return this._TRIP_ID;
			}
			set
			{
				if ((this._TRIP_ID != value))
				{
					this.OnTRIP_IDChanging(value);
					this.SendPropertyChanging();
					this._TRIP_ID = value;
					this.SendPropertyChanged("TRIP_ID");
					this.OnTRIP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITTLE", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TITTLE
		{
			get
			{
				return this._TITTLE;
			}
			set
			{
				if ((this._TITTLE != value))
				{
					this.OnTITTLEChanging(value);
					this.SendPropertyChanging();
					this._TITTLE = value;
					this.SendPropertyChanged("TITTLE");
					this.OnTITTLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(255)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUMNAILIMAGE", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string THUMNAILIMAGE
		{
			get
			{
				return this._THUMNAILIMAGE;
			}
			set
			{
				if ((this._THUMNAILIMAGE != value))
				{
					this.OnTHUMNAILIMAGEChanging(value);
					this.SendPropertyChanging();
					this._THUMNAILIMAGE = value;
					this.SendPropertyChanged("THUMNAILIMAGE");
					this.OnTHUMNAILIMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENTPROCEEDS", DbType="Float NOT NULL")]
		public double CURRENTPROCEEDS
		{
			get
			{
				return this._CURRENTPROCEEDS;
			}
			set
			{
				if ((this._CURRENTPROCEEDS != value))
				{
					this.OnCURRENTPROCEEDSChanging(value);
					this.SendPropertyChanging();
					this._CURRENTPROCEEDS = value;
					this.SendPropertyChanged("CURRENTPROCEEDS");
					this.OnCURRENTPROCEEDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALCOSTS", DbType="Float NOT NULL")]
		public double TOTALCOSTS
		{
			get
			{
				return this._TOTALCOSTS;
			}
			set
			{
				if ((this._TOTALCOSTS != value))
				{
					this.OnTOTALCOSTSChanging(value);
					this.SendPropertyChanging();
					this._TOTALCOSTS = value;
					this.SendPropertyChanged("TOTALCOSTS");
					this.OnTOTALCOSTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOGODATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> TOGODATE
		{
			get
			{
				return this._TOGODATE;
			}
			set
			{
				if ((this._TOGODATE != value))
				{
					this.OnTOGODATEChanging(value);
					this.SendPropertyChanging();
					this._TOGODATE = value;
					this.SendPropertyChanged("TOGODATE");
					this.OnTOGODATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETURNDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RETURNDATE
		{
			get
			{
				return this._RETURNDATE;
			}
			set
			{
				if ((this._RETURNDATE != value))
				{
					this.OnRETURNDATEChanging(value);
					this.SendPropertyChanging();
					this._RETURNDATE = value;
					this.SendPropertyChanged("RETURNDATE");
					this.OnRETURNDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISDONE", DbType="Bit")]
		public System.Nullable<bool> ISDONE
		{
			get
			{
				return this._ISDONE;
			}
			set
			{
				if ((this._ISDONE != value))
				{
					this.OnISDONEChanging(value);
					this.SendPropertyChanging();
					this._ISDONE = value;
					this.SendPropertyChanged("ISDONE");
					this.OnISDONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_COSTINCURRED", Storage="_TRIP_COSTINCURREDs", ThisKey="TRIP_ID", OtherKey="TRIP_ID")]
		public EntitySet<TRIP_COSTINCURRED> TRIP_COSTINCURREDs
		{
			get
			{
				return this._TRIP_COSTINCURREDs;
			}
			set
			{
				this._TRIP_COSTINCURREDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_IMAGE", Storage="_TRIP_IMAGEs", ThisKey="TRIP_ID", OtherKey="TRIP_ID")]
		public EntitySet<TRIP_IMAGE> TRIP_IMAGEs
		{
			get
			{
				return this._TRIP_IMAGEs;
			}
			set
			{
				this._TRIP_IMAGEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_LOCATION", Storage="_TRIP_LOCATIONs", ThisKey="TRIP_ID", OtherKey="TRIP_ID")]
		public EntitySet<TRIP_LOCATION> TRIP_LOCATIONs
		{
			get
			{
				return this._TRIP_LOCATIONs;
			}
			set
			{
				this._TRIP_LOCATIONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_MEMBER", Storage="_TRIP_MEMBERs", ThisKey="TRIP_ID", OtherKey="TRIP_ID")]
		public EntitySet<TRIP_MEMBER> TRIP_MEMBERs
		{
			get
			{
				return this._TRIP_MEMBERs;
			}
			set
			{
				this._TRIP_MEMBERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRIP_COSTINCURREDs(TRIP_COSTINCURRED entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = this;
		}
		
		private void detach_TRIP_COSTINCURREDs(TRIP_COSTINCURRED entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = null;
		}
		
		private void attach_TRIP_IMAGEs(TRIP_IMAGE entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = this;
		}
		
		private void detach_TRIP_IMAGEs(TRIP_IMAGE entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = null;
		}
		
		private void attach_TRIP_LOCATIONs(TRIP_LOCATION entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = this;
		}
		
		private void detach_TRIP_LOCATIONs(TRIP_LOCATION entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = null;
		}
		
		private void attach_TRIP_MEMBERs(TRIP_MEMBER entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = this;
		}
		
		private void detach_TRIP_MEMBERs(TRIP_MEMBER entity)
		{
			this.SendPropertyChanging();
			entity.TRIP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRIP_COSTINCURRED")]
	public partial class TRIP_COSTINCURRED : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _COST_ID;
		
		private int _TRIP_ID;
		
		private System.Nullable<double> _COST;
		
		private EntityRef<TRIP> _TRIP;
		
		private EntityRef<COSTINCURRED> _COSTINCURRED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOST_IDChanging(int value);
    partial void OnCOST_IDChanged();
    partial void OnTRIP_IDChanging(int value);
    partial void OnTRIP_IDChanged();
    partial void OnCOSTChanging(System.Nullable<double> value);
    partial void OnCOSTChanged();
    #endregion
		
		public TRIP_COSTINCURRED()
		{
			this._TRIP = default(EntityRef<TRIP>);
			this._COSTINCURRED = default(EntityRef<COSTINCURRED>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COST_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int COST_ID
		{
			get
			{
				return this._COST_ID;
			}
			set
			{
				if ((this._COST_ID != value))
				{
					if (this._COSTINCURRED.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOST_IDChanging(value);
					this.SendPropertyChanging();
					this._COST_ID = value;
					this.SendPropertyChanged("COST_ID");
					this.OnCOST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIP_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TRIP_ID
		{
			get
			{
				return this._TRIP_ID;
			}
			set
			{
				if ((this._TRIP_ID != value))
				{
					if (this._TRIP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTRIP_IDChanging(value);
					this.SendPropertyChanging();
					this._TRIP_ID = value;
					this.SendPropertyChanged("TRIP_ID");
					this.OnTRIP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COST", DbType="Float")]
		public System.Nullable<double> COST
		{
			get
			{
				return this._COST;
			}
			set
			{
				if ((this._COST != value))
				{
					this.OnCOSTChanging(value);
					this.SendPropertyChanging();
					this._COST = value;
					this.SendPropertyChanged("COST");
					this.OnCOSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_COSTINCURRED", Storage="_TRIP", ThisKey="TRIP_ID", OtherKey="TRIP_ID", IsForeignKey=true)]
		public TRIP TRIP
		{
			get
			{
				return this._TRIP.Entity;
			}
			set
			{
				TRIP previousValue = this._TRIP.Entity;
				if (((previousValue != value) 
							|| (this._TRIP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRIP.Entity = null;
						previousValue.TRIP_COSTINCURREDs.Remove(this);
					}
					this._TRIP.Entity = value;
					if ((value != null))
					{
						value.TRIP_COSTINCURREDs.Add(this);
						this._TRIP_ID = value.TRIP_ID;
					}
					else
					{
						this._TRIP_ID = default(int);
					}
					this.SendPropertyChanged("TRIP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COSTINCURRED_TRIP_COSTINCURRED", Storage="_COSTINCURRED", ThisKey="COST_ID", OtherKey="COST_ID", IsForeignKey=true)]
		public COSTINCURRED COSTINCURRED
		{
			get
			{
				return this._COSTINCURRED.Entity;
			}
			set
			{
				COSTINCURRED previousValue = this._COSTINCURRED.Entity;
				if (((previousValue != value) 
							|| (this._COSTINCURRED.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COSTINCURRED.Entity = null;
						previousValue.TRIP_COSTINCURREDs.Remove(this);
					}
					this._COSTINCURRED.Entity = value;
					if ((value != null))
					{
						value.TRIP_COSTINCURREDs.Add(this);
						this._COST_ID = value.COST_ID;
					}
					else
					{
						this._COST_ID = default(int);
					}
					this.SendPropertyChanged("COSTINCURRED");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRIP_IMAGES")]
	public partial class TRIP_IMAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TRIP_ID;
		
		private string _IMAGE;
		
		private EntityRef<TRIP> _TRIP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRIP_IDChanging(int value);
    partial void OnTRIP_IDChanged();
    partial void OnIMAGEChanging(string value);
    partial void OnIMAGEChanged();
    #endregion
		
		public TRIP_IMAGE()
		{
			this._TRIP = default(EntityRef<TRIP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIP_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TRIP_ID
		{
			get
			{
				return this._TRIP_ID;
			}
			set
			{
				if ((this._TRIP_ID != value))
				{
					if (this._TRIP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTRIP_IDChanging(value);
					this.SendPropertyChanging();
					this._TRIP_ID = value;
					this.SendPropertyChanged("TRIP_ID");
					this.OnTRIP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IMAGE
		{
			get
			{
				return this._IMAGE;
			}
			set
			{
				if ((this._IMAGE != value))
				{
					this.OnIMAGEChanging(value);
					this.SendPropertyChanging();
					this._IMAGE = value;
					this.SendPropertyChanged("IMAGE");
					this.OnIMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_IMAGE", Storage="_TRIP", ThisKey="TRIP_ID", OtherKey="TRIP_ID", IsForeignKey=true)]
		public TRIP TRIP
		{
			get
			{
				return this._TRIP.Entity;
			}
			set
			{
				TRIP previousValue = this._TRIP.Entity;
				if (((previousValue != value) 
							|| (this._TRIP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRIP.Entity = null;
						previousValue.TRIP_IMAGEs.Remove(this);
					}
					this._TRIP.Entity = value;
					if ((value != null))
					{
						value.TRIP_IMAGEs.Add(this);
						this._TRIP_ID = value.TRIP_ID;
					}
					else
					{
						this._TRIP_ID = default(int);
					}
					this.SendPropertyChanged("TRIP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRIP_LOCATION")]
	public partial class TRIP_LOCATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TRIP_ID;
		
		private int _LOCATION_ID;
		
		private double _COSTS;
		
		private EntityRef<LOCATION> _LOCATION;
		
		private EntityRef<TRIP> _TRIP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRIP_IDChanging(int value);
    partial void OnTRIP_IDChanged();
    partial void OnLOCATION_IDChanging(int value);
    partial void OnLOCATION_IDChanged();
    partial void OnCOSTSChanging(double value);
    partial void OnCOSTSChanged();
    #endregion
		
		public TRIP_LOCATION()
		{
			this._LOCATION = default(EntityRef<LOCATION>);
			this._TRIP = default(EntityRef<TRIP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIP_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TRIP_ID
		{
			get
			{
				return this._TRIP_ID;
			}
			set
			{
				if ((this._TRIP_ID != value))
				{
					if (this._TRIP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTRIP_IDChanging(value);
					this.SendPropertyChanging();
					this._TRIP_ID = value;
					this.SendPropertyChanged("TRIP_ID");
					this.OnTRIP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LOCATION_ID
		{
			get
			{
				return this._LOCATION_ID;
			}
			set
			{
				if ((this._LOCATION_ID != value))
				{
					if (this._LOCATION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLOCATION_IDChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_ID = value;
					this.SendPropertyChanged("LOCATION_ID");
					this.OnLOCATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTS", DbType="Float NOT NULL")]
		public double COSTS
		{
			get
			{
				return this._COSTS;
			}
			set
			{
				if ((this._COSTS != value))
				{
					this.OnCOSTSChanging(value);
					this.SendPropertyChanging();
					this._COSTS = value;
					this.SendPropertyChanged("COSTS");
					this.OnCOSTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOCATION_TRIP_LOCATION", Storage="_LOCATION", ThisKey="LOCATION_ID", OtherKey="LOCATION_ID", IsForeignKey=true)]
		public LOCATION LOCATION
		{
			get
			{
				return this._LOCATION.Entity;
			}
			set
			{
				LOCATION previousValue = this._LOCATION.Entity;
				if (((previousValue != value) 
							|| (this._LOCATION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOCATION.Entity = null;
						previousValue.TRIP_LOCATIONs.Remove(this);
					}
					this._LOCATION.Entity = value;
					if ((value != null))
					{
						value.TRIP_LOCATIONs.Add(this);
						this._LOCATION_ID = value.LOCATION_ID;
					}
					else
					{
						this._LOCATION_ID = default(int);
					}
					this.SendPropertyChanged("LOCATION");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_LOCATION", Storage="_TRIP", ThisKey="TRIP_ID", OtherKey="TRIP_ID", IsForeignKey=true)]
		public TRIP TRIP
		{
			get
			{
				return this._TRIP.Entity;
			}
			set
			{
				TRIP previousValue = this._TRIP.Entity;
				if (((previousValue != value) 
							|| (this._TRIP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRIP.Entity = null;
						previousValue.TRIP_LOCATIONs.Remove(this);
					}
					this._TRIP.Entity = value;
					if ((value != null))
					{
						value.TRIP_LOCATIONs.Add(this);
						this._TRIP_ID = value.TRIP_ID;
					}
					else
					{
						this._TRIP_ID = default(int);
					}
					this.SendPropertyChanged("TRIP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRIP_MEMBER")]
	public partial class TRIP_MEMBER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TRIP_ID;
		
		private int _MEMBER_ID;
		
		private double _AMOUNTPAID;
		
		private EntityRef<MEMBER> _MEMBER;
		
		private EntityRef<TRIP> _TRIP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRIP_IDChanging(int value);
    partial void OnTRIP_IDChanged();
    partial void OnMEMBER_IDChanging(int value);
    partial void OnMEMBER_IDChanged();
    partial void OnAMOUNTPAIDChanging(double value);
    partial void OnAMOUNTPAIDChanged();
    #endregion
		
		public TRIP_MEMBER()
		{
			this._MEMBER = default(EntityRef<MEMBER>);
			this._TRIP = default(EntityRef<TRIP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIP_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TRIP_ID
		{
			get
			{
				return this._TRIP_ID;
			}
			set
			{
				if ((this._TRIP_ID != value))
				{
					if (this._TRIP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTRIP_IDChanging(value);
					this.SendPropertyChanging();
					this._TRIP_ID = value;
					this.SendPropertyChanged("TRIP_ID");
					this.OnTRIP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MEMBER_ID
		{
			get
			{
				return this._MEMBER_ID;
			}
			set
			{
				if ((this._MEMBER_ID != value))
				{
					if (this._MEMBER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMEMBER_IDChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_ID = value;
					this.SendPropertyChanged("MEMBER_ID");
					this.OnMEMBER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNTPAID", DbType="Float NOT NULL")]
		public double AMOUNTPAID
		{
			get
			{
				return this._AMOUNTPAID;
			}
			set
			{
				if ((this._AMOUNTPAID != value))
				{
					this.OnAMOUNTPAIDChanging(value);
					this.SendPropertyChanging();
					this._AMOUNTPAID = value;
					this.SendPropertyChanged("AMOUNTPAID");
					this.OnAMOUNTPAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MEMBER_TRIP_MEMBER", Storage="_MEMBER", ThisKey="MEMBER_ID", OtherKey="MEMBER_ID", IsForeignKey=true)]
		public MEMBER MEMBER
		{
			get
			{
				return this._MEMBER.Entity;
			}
			set
			{
				MEMBER previousValue = this._MEMBER.Entity;
				if (((previousValue != value) 
							|| (this._MEMBER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MEMBER.Entity = null;
						previousValue.TRIP_MEMBERs.Remove(this);
					}
					this._MEMBER.Entity = value;
					if ((value != null))
					{
						value.TRIP_MEMBERs.Add(this);
						this._MEMBER_ID = value.MEMBER_ID;
					}
					else
					{
						this._MEMBER_ID = default(int);
					}
					this.SendPropertyChanged("MEMBER");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRIP_TRIP_MEMBER", Storage="_TRIP", ThisKey="TRIP_ID", OtherKey="TRIP_ID", IsForeignKey=true)]
		public TRIP TRIP
		{
			get
			{
				return this._TRIP.Entity;
			}
			set
			{
				TRIP previousValue = this._TRIP.Entity;
				if (((previousValue != value) 
							|| (this._TRIP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRIP.Entity = null;
						previousValue.TRIP_MEMBERs.Remove(this);
					}
					this._TRIP.Entity = value;
					if ((value != null))
					{
						value.TRIP_MEMBERs.Add(this);
						this._TRIP_ID = value.TRIP_ID;
					}
					else
					{
						this._TRIP_ID = default(int);
					}
					this.SendPropertyChanged("TRIP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COSTINCURRED")]
	public partial class COSTINCURRED : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _COST_ID;
		
		private string _NAME;
		
		private EntitySet<TRIP_COSTINCURRED> _TRIP_COSTINCURREDs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOST_IDChanging(int value);
    partial void OnCOST_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public COSTINCURRED()
		{
			this._TRIP_COSTINCURREDs = new EntitySet<TRIP_COSTINCURRED>(new Action<TRIP_COSTINCURRED>(this.attach_TRIP_COSTINCURREDs), new Action<TRIP_COSTINCURRED>(this.detach_TRIP_COSTINCURREDs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COST_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int COST_ID
		{
			get
			{
				return this._COST_ID;
			}
			set
			{
				if ((this._COST_ID != value))
				{
					this.OnCOST_IDChanging(value);
					this.SendPropertyChanging();
					this._COST_ID = value;
					this.SendPropertyChanged("COST_ID");
					this.OnCOST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COSTINCURRED_TRIP_COSTINCURRED", Storage="_TRIP_COSTINCURREDs", ThisKey="COST_ID", OtherKey="COST_ID")]
		public EntitySet<TRIP_COSTINCURRED> TRIP_COSTINCURREDs
		{
			get
			{
				return this._TRIP_COSTINCURREDs;
			}
			set
			{
				this._TRIP_COSTINCURREDs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRIP_COSTINCURREDs(TRIP_COSTINCURRED entity)
		{
			this.SendPropertyChanging();
			entity.COSTINCURRED = this;
		}
		
		private void detach_TRIP_COSTINCURREDs(TRIP_COSTINCURRED entity)
		{
			this.SendPropertyChanging();
			entity.COSTINCURRED = null;
		}
	}
}
#pragma warning restore 1591
