//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using PropertyChanged;

namespace WeSplitApp
{
    using System;
    using System.Collections.ObjectModel;

    [AddINotifyPropertyChangedInterface]
    public partial class COSTINCURRED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COSTINCURRED()
        {
            this.TRIP_COSTINCURRED = new ObservableCollection<TRIP_COSTINCURRED>();
        }
    
        public int COST_ID { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TRIP_COSTINCURRED> TRIP_COSTINCURRED { get; set; }
    }
}
