//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using PropertyChanged;

namespace WeSplitApp
{
    using System;
    using System.Collections.ObjectModel;

    [AddINotifyPropertyChangedInterface]
    public partial class LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCATION()
        {
            this.TRIP_LOCATION = new ObservableCollection<TRIP_LOCATION>();
        }
    
        public int LOCATION_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TRIP_LOCATION> TRIP_LOCATION { get; set; }
    }
}
