//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBER()
        {
            this.TRIP_MEMBER = new ObservableCollection<TRIP_MEMBER>();
        }
    
        public int MEMBER_ID { get; set; }
        public string NAME { get; set; }
        public string PHONENUMBER { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public string AVATAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TRIP_MEMBER> TRIP_MEMBER { get; set; }
    }
}
