//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TRIP_LOCATION
    {
        public int TRIP_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public double COSTS { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        public virtual TRIP TRIP { get; set; }
    }
}
