//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WESPLITAPPEntities : DbContext
    {
        public WESPLITAPPEntities()
            : base("name=WESPLITAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COSTINCURRED> COSTINCURREDS { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<MEMBER> MEMBERS { get; set; }
        public virtual DbSet<TRIP> TRIPS { get; set; }
        public virtual DbSet<TRIP_COSTINCURRED> TRIP_COSTINCURRED { get; set; }
        public virtual DbSet<TRIP_LOCATION> TRIP_LOCATION { get; set; }
        public virtual DbSet<TRIP_MEMBER> TRIP_MEMBER { get; set; }
        public virtual DbSet<TRIP_IMAGES> TRIP_IMAGES { get; set; }
    }
}
